name: 'Deploy WordPress'
description: 'Deploy WordPress code to a server'
author: 'rtCamp'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/rtcamp/action-deploy-wordpress:v3.2.0'
branding:
  icon: 'upload-cloud'
  color: 'yellow'
