on:
  push:
    tags:
      - "v*"
name: Release Creation

permissions:
  contents: write

jobs:
  release:
    name: Create a Draft Release on GitHub
    runs-on: ubuntu-latest
    steps:
    - name: Get Release Name
      id: get_release_name
      run: |
        echo "release_name=${GITHUB_REF_NAME/v/Version }" >> $GITHUB_ENV
    - name: Publish a Draft Release
      uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
      with:
        draft: true  # Creates a Draft Release
        name: ${{ env.release_name }}
        generate_release_notes: true
